export const COMPETITIVE_CITIES = [
  "new york","nyc","brooklyn","manhattan","queens","bronx",
  "los angeles","la","san francisco","sf","palo alto","cupertino","san jose","menlo park","mountain view",
  "boston","cambridge","brookline","lexington","newton","concord",
  "chicago","evanston","naperville","lake forest","winnetka",
  "washington dc","dc","bethesda","mclean","potomac","chevy chase","great falls",
  "seattle","bellevue","redmond","mercer island","kirkland",
  "houston","dallas","austin","plano","frisco",
  "miami","coral gables","boca raton",
  "atlanta","johns creek","alpharetta",
  "princeton","greenwich","fairfield","westport","darien","new canaan",
  "scarsdale","great neck","syosset","jericho","manhasset","chappaqua",
  "irvine","fremont","pleasanton","walnut creek","dublin",
  "ann arbor","troy","birmingham","bloomfield hills",
  "minneapolis","eden prairie","edina","wayzata",
  "richmond","mclean","potomac","rockville",
];

export const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL",
  "GA","HI","ID","IL","IN","IA","KS","KY","LA","ME",
  "MD","MA","MI","MN","MS","MO","MT","NE","NV","NH",
  "NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI",
  "SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
];

export const MAJORS = [
  "Computer Science","Software Engineering","Data Science","Artificial Intelligence",
  "Electrical Engineering","Mechanical Engineering","Civil Engineering",
  "Chemical Engineering","Aerospace Engineering","Biomedical Engineering",
  "Engineering (General)","Mathematics","Statistics","Physics",
  "Biology","Chemistry","Neuroscience","Environmental Science","Biochemistry",
  "Pre-Med","Nursing","Public Health","Pharmacy","Kinesiology",
  "Economics","Business Administration","Finance","Accounting","Marketing",
  "Political Science","International Relations","Public Policy","Law (Pre-Law)",
  "History","Philosophy","English","Linguistics","Journalism","Communications",
  "Psychology","Sociology","Anthropology","Education","Social Work",
  "Architecture","Urban Planning","Design","Film","Music","Theater","Art",
  "Agriculture","Veterinary","Forestry","Marine Biology","Undecided",
];

export const AP_COURSES = [
  "AP Calculus AB","AP Calculus BC","AP Statistics","AP Precalculus",
  "AP Physics 1","AP Physics 2","AP Physics C: Mechanics","AP Physics C: E&M",
  "AP Chemistry","AP Biology","AP Environmental Science",
  "AP Computer Science A","AP Computer Science Principles",
  "AP US History","AP World History","AP European History","AP African American Studies",
  "AP US Government","AP Comparative Government","AP Economics (Macro)","AP Economics (Micro)",
  "AP English Language","AP English Literature",
  "AP Spanish Language","AP Spanish Literature","AP French Language",
  "AP Mandarin","AP Latin","AP Japanese","AP Italian","AP German",
  "AP Psychology","AP Art History","AP Music Theory",
  "AP Studio Art: Drawing","AP Studio Art: 2D","AP Studio Art: 3D",
  "AP Human Geography","AP Seminar","AP Research",
];

export const HONORS_COURSES = [
  "Honors English","Honors Math","Honors Algebra II","Honors Pre-Calculus",
  "Honors Biology","Honors Chemistry","Honors Physics",
  "Honors History","Honors World History","Honors US History",
  "Honors Spanish","Honors French","Honors Economics",
  "Honors Computer Science",
  "Honors Intro to Engineering","Honors Principles of Engineering",
  "Honors Medical Intervention","Honors Principles of Biomedical Science",
  "Honors Human Body Systems","Dual Enrollment (College Course)",
  "IB Higher Level (HL) Course","IB Standard Level (SL) Course",
];

export const LANGUAGES = [
  "Spanish","French","Mandarin","Japanese","German",
  "Arabic","Portuguese","Korean","Italian","Latin",
  "Hindi","Russian","Farsi","Vietnamese","Tagalog",
  "ASL (American Sign Language)","Hebrew","Turkish","Polish",
];

export const LEADERSHIP_ROLES = [
  { label: "Student Body President", score: 10 },
  { label: "Student Body Vice President", score: 9 },
  { label: "Class President", score: 8 },
  { label: "Club President/Founder", score: 9 },
  { label: "Club Vice President", score: 7 },
  { label: "Team Captain (Varsity)", score: 8 },
  { label: "Team Captain (JV)", score: 6 },
  { label: "NHS President", score: 8 },
  { label: "NHS Member", score: 5 },
  { label: "Editor-in-Chief (Newspaper/Yearbook)", score: 8 },
  { label: "Eagle Scout / Gold Award", score: 9 },
  { label: "Debate Team Captain", score: 7 },
  { label: "Orchestra/Band First Chair", score: 7 },
  { label: "Math Olympiad / Science Olympiad Lead", score: 8 },
  { label: "Volunteer Coordinator", score: 6 },
  { label: "Peer Tutor / Mentor", score: 5 },
  { label: "Research Lab Assistant", score: 7 },
  { label: "Internship (Competitive)", score: 7 },
  { label: "Small Business Owner", score: 8 },
  { label: "Published Author / Researcher", score: 9 },
  { label: "State/National Competition Winner", score: 10 },
  { label: "Community Service Leader (100+ hrs)", score: 6 },
  { label: "Model UN Chair/Secretary General", score: 8 },
  { label: "DECA/FBLA Officer", score: 7 },
  { label: "HOSA Officer", score: 7 },
];

export const AWARDS = [
  { label: "National Merit Finalist", score: 10, category: "academic" },
  { label: "National Merit Semifinalist", score: 9, category: "academic" },
  { label: "National Merit Commended", score: 7, category: "academic" },
  { label: "AP Scholar with Distinction", score: 7, category: "academic" },
  { label: "AP Scholar with Honor", score: 6, category: "academic" },
  { label: "AP Scholar", score: 5, category: "academic" },
  { label: "Valedictorian", score: 10, category: "academic" },
  { label: "Salutatorian", score: 9, category: "academic" },
  { label: "National Honor Society", score: 5, category: "academic" },
  { label: "IB Diploma (36+)", score: 8, category: "academic" },
  { label: "USAMO / USAJMO Qualifier", score: 10, category: "stem" },
  { label: "AMC 10/12 Top Score (AIME Qualifier)", score: 8, category: "stem" },
  { label: "Science Olympiad State/National Medal", score: 9, category: "stem" },
  { label: "ISEF Finalist", score: 10, category: "stem" },
  { label: "Regeneron STS Scholar", score: 10, category: "stem" },
  { label: "First Robotics Dean's List", score: 9, category: "stem" },
  { label: "Congressional App Challenge Winner", score: 9, category: "stem" },
  { label: "Physics Olympiad (USAPhO)", score: 10, category: "stem" },
  { label: "Chemistry Olympiad (USNCO)", score: 9, category: "stem" },
  { label: "Biology Olympiad (USABO)", score: 9, category: "stem" },
  { label: "National Scholastic Art Gold Key", score: 8, category: "arts" },
  { label: "National Scholastic Writing Gold Key", score: 8, category: "arts" },
  { label: "YoungArts Winner", score: 9, category: "arts" },
  { label: "National Speech & Debate Award", score: 8, category: "arts" },
  { label: "All-State Athlete", score: 9, category: "athletics" },
  { label: "All-Region Athlete", score: 7, category: "athletics" },
  { label: "Team State Championship", score: 8, category: "athletics" },
  { label: "Presidential Volunteer Service Award (Gold)", score: 7, category: "community" },
  { label: "Eagle Scout / Gold Award", score: 9, category: "community" },
  { label: "State/Regional Leadership Award", score: 7, category: "community" },
];

export const MAJOR_GROUPS = {
  "Computer Science": "cs_tech", "Software Engineering": "cs_tech",
  "Data Science": "cs_tech", "Artificial Intelligence": "cs_tech",
  "Electrical Engineering": "engineering", "Mechanical Engineering": "engineering",
  "Civil Engineering": "engineering", "Chemical Engineering": "engineering",
  "Aerospace Engineering": "engineering", "Biomedical Engineering": "engineering",
  "Engineering (General)": "engineering",
  "Mathematics": "math_science", "Statistics": "math_science", "Physics": "math_science",
  "Biology": "bio_health", "Chemistry": "bio_health", "Neuroscience": "bio_health",
  "Environmental Science": "bio_health", "Biochemistry": "bio_health",
  "Pre-Med": "bio_health", "Nursing": "bio_health", "Public Health": "bio_health",
  "Pharmacy": "bio_health", "Kinesiology": "bio_health",
  "Economics": "business_econ", "Business Administration": "business_econ",
  "Finance": "business_econ", "Accounting": "business_econ", "Marketing": "business_econ",
  "Political Science": "humanities_social", "International Relations": "humanities_social",
  "Public Policy": "humanities_social", "Law (Pre-Law)": "humanities_social",
  "History": "humanities_social", "Philosophy": "humanities_social",
  "English": "humanities_social", "Linguistics": "humanities_social",
  "Journalism": "humanities_social", "Communications": "humanities_social",
  "Psychology": "humanities_social", "Sociology": "humanities_social",
  "Anthropology": "humanities_social", "Education": "humanities_social",
  "Social Work": "humanities_social",
  "Architecture": "arts_design", "Urban Planning": "arts_design",
  "Design": "arts_design", "Film": "arts_design", "Music": "arts_design",
  "Theater": "arts_design", "Art": "arts_design",
  "Agriculture": "agriculture", "Veterinary": "agriculture",
  "Forestry": "agriculture", "Marine Biology": "agriculture",
  "Undecided": "undecided",
};

// Schools that heavily track demonstrated interest
export const DI_SCHOOLS = [
  "Northeastern","Tulane","Colgate University","Bucknell","Denison",
  "University of Denver","Elon","Rollins","Butler","Furman",
  "Wake Forest","Boston University","Syracuse University","American University",
  "University of Miami","Villanova","Santa Clara University",
];

export const MAJOR_EC_SUGGESTIONS = {
  "Computer Science": ["Competitive Programming","Hackathon Winner","Personal Projects (Apps/Websites)","Robotics Club","AI/ML Research","Open Source Contributor"],
  "Software Engineering": ["Hackathon Winner","Personal Projects","Open Source Contributor","Robotics Club","Competitive Programming"],
  "Data Science": ["Kaggle Competitions","Research Data Projects","Math Club","Statistics Research","Hackathons"],
  "Artificial Intelligence": ["AI/ML Research","Hackathons","Robotics Club","Personal AI Projects","Research Lab"],
  "Electrical Engineering": ["Robotics Club","Electronics Club","Ham Radio","Arduino/Raspberry Pi Projects","IEEE Student Chapter"],
  "Mechanical Engineering": ["Robotics Club","FIRST Robotics","3D Printing Club","Physics Olympiad","Engineering Competitions"],
  "Aerospace Engineering": ["Rocketry Club","Model Aviation","Robotics","Physics Olympiad","NASA Internship"],
  "Biomedical Engineering": ["Hospital Volunteering","Research Lab Assistant","HOSA","Science Fair","Red Cross Club"],
  "Engineering (General)": ["Robotics Club","Science Olympiad","Engineering Club","FIRST Robotics","Physics Olympiad"],
  "Mathematics": ["Math Olympiad (USAMO/AMC)","Math Tutoring","Statistics Research","Coding Club","Math League"],
  "Physics": ["Physics Olympiad","Research Lab","Science Olympiad","Robotics Club","Astronomy Club"],
  "Biology": ["Research Lab Assistant","Science Fair","Hospital Volunteering","Environmental Club","HOSA"],
  "Chemistry": ["Research Lab Assistant","Science Fair","Science Olympiad (Chem)","Chemistry Club"],
  "Neuroscience": ["Research Lab Assistant","Brain Bee Competition","Hospital Volunteering","HOSA","Psychology Club"],
  "Pre-Med": ["Hospital/Clinic Volunteering","HOSA","Research Lab Assistant","EMT Certification","Red Cross Club"],
  "Nursing": ["Hospital Volunteering","CNA Certification","HOSA","Red Cross Club","Community Health Events"],
  "Economics": ["DECA","Stock Market Club","Economics Olympiad","Model UN","Financial Literacy Tutoring"],
  "Business Administration": ["DECA","FBLA","Entrepreneurship Club","Small Business Owner","Internship"],
  "Finance": ["Stock Market Club","DECA","Finance Internship","Economics Club","Model UN"],
  "Political Science": ["Model UN","Student Government","Debate Team","Government Internship","Political Campaign Volunteer"],
  "Journalism": ["School Newspaper Editor","Broadcast/Podcast","Photography Club","Writing Competitions","Press Club"],
  "Communications": ["Student Government","School News Anchor","Debate","Marketing Club","Social Media Manager"],
  "Psychology": ["Peer Counseling","Mental Health Awareness Club","Research Lab","Hospital Volunteering","HOSA"],
  "Film": ["Film Club","Short Film Director","Yearbook/Media Team","YouTube Channel","School News Anchor"],
  "Music": ["Orchestra/Band","Jazz Band","Choir","Music Composition","Private Music Teaching"],
  "Architecture": ["Architecture Club","Urban Planning Projects","CAD Design","Art Portfolio","Engineering Competitions"],
  "Agriculture": ["FFA","4-H Club","Farm Volunteer","Environmental Club","Science Fair (Agri)"],
  "Undecided": ["Student Government","Debate Team","Volunteering","Sports (Varsity)","Club Leadership","Research"],
  "default": ["Student Government","Debate Team","Volunteering","Sports (Varsity)","Club Leadership"],
};

export const COLLEGES = [
  { name: "MIT", satMid: 1580, actMid: 36, gpaMid: 4.17, acceptRate: 0.04, ecWeight: 0.95, essayWeight: 0.90, strongGroups: ["cs_tech","engineering","math_science"], state: "MA", isPublic: false, location: "Urban", website: "mit.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Harvard", satMid: 1580, actMid: 36, gpaMid: 4.18, acceptRate: 0.03, ecWeight: 0.98, essayWeight: 0.97, strongGroups: ["bio_health","humanities_social","business_econ","math_science"], state: "MA", isPublic: false, location: "Urban", website: "harvard.edu", legacyBoost: 4.0, diTracked: false, genderNeutral: true },
  { name: "Stanford", satMid: 1570, actMid: 35, gpaMid: 4.18, acceptRate: 0.04, ecWeight: 0.97, essayWeight: 0.95, strongGroups: ["cs_tech","engineering","business_econ","humanities_social"], state: "CA", isPublic: false, location: "Suburban", website: "stanford.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Princeton", satMid: 1570, actMid: 35, gpaMid: 3.90, acceptRate: 0.04, ecWeight: 0.96, essayWeight: 0.95, strongGroups: ["math_science","humanities_social","engineering","business_econ"], state: "NJ", isPublic: false, location: "Suburban", website: "princeton.edu", legacyBoost: 3.0, diTracked: false, genderNeutral: true },
  { name: "Yale", satMid: 1560, actMid: 35, gpaMid: 4.10, acceptRate: 0.05, ecWeight: 0.96, essayWeight: 0.97, strongGroups: ["humanities_social","arts_design","bio_health","business_econ"], state: "CT", isPublic: false, location: "Urban", website: "yale.edu", legacyBoost: 3.0, diTracked: false, genderNeutral: true },
  { name: "Columbia", satMid: 1560, actMid: 35, gpaMid: 4.12, acceptRate: 0.04, ecWeight: 0.94, essayWeight: 0.94, strongGroups: ["humanities_social","engineering","business_econ","cs_tech"], state: "NY", isPublic: false, location: "Urban", website: "columbia.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "UPenn", satMid: 1530, actMid: 35, gpaMid: 3.90, acceptRate: 0.07, ecWeight: 0.93, essayWeight: 0.92, strongGroups: ["business_econ","bio_health","engineering","humanities_social"], state: "PA", isPublic: false, location: "Urban", website: "upenn.edu", legacyBoost: 3.5, diTracked: false, genderNeutral: true },
  { name: "Brown", satMid: 1530, actMid: 35, gpaMid: 4.05, acceptRate: 0.05, ecWeight: 0.93, essayWeight: 0.94, strongGroups: ["humanities_social","cs_tech","bio_health","arts_design"], state: "RI", isPublic: false, location: "Urban", website: "brown.edu", legacyBoost: 2.5, diTracked: false, genderNeutral: true },
  { name: "Dartmouth", satMid: 1530, actMid: 34, gpaMid: 3.99, acceptRate: 0.06, ecWeight: 0.92, essayWeight: 0.93, strongGroups: ["business_econ","humanities_social","engineering"], state: "NH", isPublic: false, location: "Rural", website: "dartmouth.edu", legacyBoost: 4.0, diTracked: false, genderNeutral: true },
  { name: "Cornell", satMid: 1510, actMid: 34, gpaMid: 4.05, acceptRate: 0.07, ecWeight: 0.90, essayWeight: 0.88, strongGroups: ["engineering","bio_health","business_econ","agriculture","cs_tech"], state: "NY", isPublic: false, location: "Suburban", website: "cornell.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Duke", satMid: 1540, actMid: 35, gpaMid: 4.13, acceptRate: 0.06, ecWeight: 0.92, essayWeight: 0.91, strongGroups: ["bio_health","business_econ","humanities_social","engineering"], state: "NC", isPublic: false, location: "Suburban", website: "duke.edu", legacyBoost: 2.5, diTracked: false, genderNeutral: true },
  { name: "Northwestern", satMid: 1530, actMid: 34, gpaMid: 4.10, acceptRate: 0.07, ecWeight: 0.91, essayWeight: 0.91, strongGroups: ["humanities_social","arts_design","engineering","business_econ"], state: "IL", isPublic: false, location: "Suburban", website: "northwestern.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Johns Hopkins", satMid: 1540, actMid: 35, gpaMid: 3.92, acceptRate: 0.07, ecWeight: 0.90, essayWeight: 0.89, strongGroups: ["bio_health","engineering","cs_tech","humanities_social"], state: "MD", isPublic: false, location: "Urban", website: "jhu.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Vanderbilt", satMid: 1530, actMid: 34, gpaMid: 3.83, acceptRate: 0.07, ecWeight: 0.89, essayWeight: 0.89, strongGroups: ["bio_health","business_econ","engineering","humanities_social"], state: "TN", isPublic: false, location: "Urban", website: "vanderbilt.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Rice", satMid: 1540, actMid: 35, gpaMid: 4.12, acceptRate: 0.08, ecWeight: 0.91, essayWeight: 0.90, strongGroups: ["engineering","math_science","arts_design","cs_tech"], state: "TX", isPublic: false, location: "Urban", website: "rice.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "WashU St. Louis", satMid: 1530, actMid: 34, gpaMid: 4.05, acceptRate: 0.12, ecWeight: 0.88, essayWeight: 0.88, strongGroups: ["business_econ","engineering","bio_health","arts_design"], state: "MO", isPublic: false, location: "Suburban", website: "wustl.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Notre Dame", satMid: 1510, actMid: 34, gpaMid: 4.06, acceptRate: 0.12, ecWeight: 0.88, essayWeight: 0.87, strongGroups: ["business_econ","engineering","humanities_social"], state: "IN", isPublic: false, location: "Suburban", website: "nd.edu", legacyBoost: 2.5, diTracked: false, genderNeutral: true },
  { name: "Georgetown", satMid: 1480, actMid: 33, gpaMid: 3.90, acceptRate: 0.12, ecWeight: 0.87, essayWeight: 0.89, strongGroups: ["humanities_social","business_econ","bio_health"], state: "DC", isPublic: false, location: "Urban", website: "georgetown.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Carnegie Mellon", satMid: 1540, actMid: 35, gpaMid: 3.84, acceptRate: 0.11, ecWeight: 0.88, essayWeight: 0.85, strongGroups: ["cs_tech","engineering","arts_design","business_econ"], state: "PA", isPublic: false, location: "Urban", website: "cmu.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "Emory", satMid: 1480, actMid: 33, gpaMid: 3.90, acceptRate: 0.11, ecWeight: 0.86, essayWeight: 0.87, strongGroups: ["bio_health","business_econ","humanities_social"], state: "GA", isPublic: false, location: "Suburban", website: "emory.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "USC", satMid: 1460, actMid: 33, gpaMid: 3.79, acceptRate: 0.13, ecWeight: 0.85, essayWeight: 0.84, strongGroups: ["arts_design","business_econ","engineering","cs_tech"], state: "CA", isPublic: false, location: "Urban", website: "usc.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Tufts", satMid: 1480, actMid: 33, gpaMid: 3.92, acceptRate: 0.11, ecWeight: 0.88, essayWeight: 0.90, strongGroups: ["humanities_social","bio_health","engineering","cs_tech"], state: "MA", isPublic: false, location: "Suburban", website: "tufts.edu", legacyBoost: 1.5, diTracked: true, genderNeutral: true },
  { name: "NYU", satMid: 1480, actMid: 33, gpaMid: 3.70, acceptRate: 0.13, ecWeight: 0.83, essayWeight: 0.86, strongGroups: ["business_econ","arts_design","humanities_social","cs_tech"], state: "NY", isPublic: false, location: "Urban", website: "nyu.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "Northeastern", satMid: 1500, actMid: 34, gpaMid: 3.90, acceptRate: 0.07, ecWeight: 0.85, essayWeight: 0.83, strongGroups: ["cs_tech","engineering","business_econ","bio_health"], state: "MA", isPublic: false, location: "Urban", website: "northeastern.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Boston University", satMid: 1430, actMid: 33, gpaMid: 3.80, acceptRate: 0.19, ecWeight: 0.80, essayWeight: 0.82, strongGroups: ["bio_health","business_econ","humanities_social","engineering"], state: "MA", isPublic: false, location: "Urban", website: "bu.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Tulane", satMid: 1430, actMid: 32, gpaMid: 3.60, acceptRate: 0.13, ecWeight: 0.82, essayWeight: 0.85, strongGroups: ["business_econ","bio_health","humanities_social","arts_design"], state: "LA", isPublic: false, location: "Urban", website: "tulane.edu", legacyBoost: 1.5, diTracked: true, genderNeutral: true },
  { name: "Wake Forest", satMid: 1430, actMid: 32, gpaMid: 3.80, acceptRate: 0.24, ecWeight: 0.85, essayWeight: 0.88, strongGroups: ["business_econ","humanities_social","bio_health"], state: "NC", isPublic: false, location: "Suburban", website: "wfu.edu", legacyBoost: 1.5, diTracked: true, genderNeutral: true },
  { name: "Boston College", satMid: 1450, actMid: 33, gpaMid: 3.90, acceptRate: 0.17, ecWeight: 0.84, essayWeight: 0.86, strongGroups: ["business_econ","humanities_social","bio_health"], state: "MA", isPublic: false, location: "Suburban", website: "bc.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Williams College", satMid: 1540, actMid: 35, gpaMid: 4.00, acceptRate: 0.09, ecWeight: 0.92, essayWeight: 0.94, strongGroups: ["humanities_social","math_science","arts_design"], state: "MA", isPublic: false, location: "Rural", website: "williams.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Amherst College", satMid: 1530, actMid: 35, gpaMid: 4.00, acceptRate: 0.09, ecWeight: 0.92, essayWeight: 0.94, strongGroups: ["humanities_social","math_science"], state: "MA", isPublic: false, location: "Rural", website: "amherst.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Swarthmore", satMid: 1530, actMid: 35, gpaMid: 3.90, acceptRate: 0.09, ecWeight: 0.91, essayWeight: 0.93, strongGroups: ["humanities_social","math_science","engineering"], state: "PA", isPublic: false, location: "Suburban", website: "swarthmore.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Pomona College", satMid: 1520, actMid: 35, gpaMid: 3.90, acceptRate: 0.08, ecWeight: 0.91, essayWeight: 0.93, strongGroups: ["humanities_social","math_science","cs_tech"], state: "CA", isPublic: false, location: "Suburban", website: "pomona.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Harvey Mudd", satMid: 1560, actMid: 36, gpaMid: 4.10, acceptRate: 0.11, ecWeight: 0.88, essayWeight: 0.85, strongGroups: ["cs_tech","engineering","math_science"], state: "CA", isPublic: false, location: "Suburban", website: "hmc.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "Wellesley", satMid: 1480, actMid: 33, gpaMid: 3.90, acceptRate: 0.17, ecWeight: 0.90, essayWeight: 0.92, strongGroups: ["humanities_social","math_science","bio_health"], state: "MA", isPublic: false, location: "Suburban", website: "wellesley.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: false },
  { name: "Bowdoin", satMid: 1490, actMid: 34, gpaMid: 3.90, acceptRate: 0.09, ecWeight: 0.91, essayWeight: 0.93, strongGroups: ["humanities_social","bio_health","arts_design"], state: "ME", isPublic: false, location: "Rural", website: "bowdoin.edu", legacyBoost: 2.0, diTracked: false, genderNeutral: true },
  { name: "Middlebury", satMid: 1450, actMid: 33, gpaMid: 3.85, acceptRate: 0.15, ecWeight: 0.88, essayWeight: 0.90, strongGroups: ["humanities_social","arts_design","agriculture"], state: "VT", isPublic: false, location: "Rural", website: "middlebury.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Colgate University", satMid: 1440, actMid: 33, gpaMid: 3.80, acceptRate: 0.24, ecWeight: 0.85, essayWeight: 0.87, strongGroups: ["humanities_social","business_econ","bio_health"], state: "NY", isPublic: false, location: "Rural", website: "colgate.edu", legacyBoost: 1.5, diTracked: true, genderNeutral: true },
  { name: "Vassar College", satMid: 1440, actMid: 33, gpaMid: 3.80, acceptRate: 0.24, ecWeight: 0.87, essayWeight: 0.91, strongGroups: ["humanities_social","arts_design","math_science"], state: "NY", isPublic: false, location: "Suburban", website: "vassar.edu", legacyBoost: 1.5, diTracked: false, genderNeutral: true },
  { name: "Case Western Reserve", satMid: 1500, actMid: 34, gpaMid: 3.85, acceptRate: 0.27, ecWeight: 0.80, essayWeight: 0.78, strongGroups: ["engineering","bio_health","cs_tech","math_science"], state: "OH", isPublic: false, location: "Urban", website: "case.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "Rochester", satMid: 1470, actMid: 33, gpaMid: 3.80, acceptRate: 0.30, ecWeight: 0.78, essayWeight: 0.80, strongGroups: ["cs_tech","engineering","bio_health","arts_design"], state: "NY", isPublic: false, location: "Urban", website: "rochester.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "Villanova", satMid: 1380, actMid: 32, gpaMid: 3.90, acceptRate: 0.28, ecWeight: 0.80, essayWeight: 0.82, strongGroups: ["business_econ","engineering","humanities_social","bio_health"], state: "PA", isPublic: false, location: "Suburban", website: "villanova.edu", legacyBoost: 1.5, diTracked: true, genderNeutral: true },
  { name: "Babson College", satMid: 1350, actMid: 30, gpaMid: 3.70, acceptRate: 0.24, ecWeight: 0.82, essayWeight: 0.80, strongGroups: ["business_econ"], state: "MA", isPublic: false, location: "Suburban", website: "babson.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Lehigh University", satMid: 1380, actMid: 31, gpaMid: 3.70, acceptRate: 0.39, ecWeight: 0.75, essayWeight: 0.74, strongGroups: ["engineering","business_econ","cs_tech"], state: "PA", isPublic: false, location: "Suburban", website: "lehigh.edu", legacyBoost: 1.3, diTracked: true, genderNeutral: true },
  { name: "George Washington University", satMid: 1370, actMid: 31, gpaMid: 3.70, acceptRate: 0.43, ecWeight: 0.78, essayWeight: 0.80, strongGroups: ["humanities_social","business_econ","bio_health"], state: "DC", isPublic: false, location: "Urban", website: "gwu.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "American University", satMid: 1310, actMid: 30, gpaMid: 3.70, acceptRate: 0.37, ecWeight: 0.76, essayWeight: 0.82, strongGroups: ["humanities_social","business_econ","arts_design"], state: "DC", isPublic: false, location: "Urban", website: "american.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Fordham University", satMid: 1320, actMid: 30, gpaMid: 3.70, acceptRate: 0.54, ecWeight: 0.74, essayWeight: 0.78, strongGroups: ["business_econ","humanities_social","bio_health"], state: "NY", isPublic: false, location: "Urban", website: "fordham.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "Syracuse University", satMid: 1270, actMid: 28, gpaMid: 3.60, acceptRate: 0.60, ecWeight: 0.68, essayWeight: 0.72, strongGroups: ["humanities_social","arts_design","business_econ","cs_tech"], state: "NY", isPublic: false, location: "Urban", website: "syracuse.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "University of Miami", satMid: 1370, actMid: 31, gpaMid: 3.80, acceptRate: 0.27, ecWeight: 0.78, essayWeight: 0.80, strongGroups: ["business_econ","bio_health","arts_design","humanities_social"], state: "FL", isPublic: false, location: "Urban", website: "miami.edu", legacyBoost: 1.3, diTracked: true, genderNeutral: true },
  { name: "Pepperdine", satMid: 1300, actMid: 29, gpaMid: 3.80, acceptRate: 0.37, ecWeight: 0.76, essayWeight: 0.80, strongGroups: ["business_econ","humanities_social","arts_design"], state: "CA", isPublic: false, location: "Suburban", website: "pepperdine.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Loyola Marymount (LMU)", satMid: 1280, actMid: 29, gpaMid: 3.70, acceptRate: 0.49, ecWeight: 0.74, essayWeight: 0.76, strongGroups: ["business_econ","arts_design","humanities_social","bio_health"], state: "CA", isPublic: false, location: "Urban", website: "lmu.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Santa Clara University", satMid: 1340, actMid: 30, gpaMid: 3.75, acceptRate: 0.49, ecWeight: 0.76, essayWeight: 0.77, strongGroups: ["business_econ","engineering","cs_tech","humanities_social"], state: "CA", isPublic: false, location: "Suburban", website: "scu.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "University of Denver", satMid: 1240, actMid: 28, gpaMid: 3.65, acceptRate: 0.58, ecWeight: 0.72, essayWeight: 0.74, strongGroups: ["business_econ","humanities_social","cs_tech"], state: "CO", isPublic: false, location: "Urban", website: "du.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Chapman University", satMid: 1250, actMid: 28, gpaMid: 3.65, acceptRate: 0.57, ecWeight: 0.74, essayWeight: 0.78, strongGroups: ["arts_design","business_econ","bio_health","humanities_social"], state: "CA", isPublic: false, location: "Suburban", website: "chapman.edu", legacyBoost: 1.2, diTracked: true, genderNeutral: true },
  { name: "Drexel University", satMid: 1300, actMid: 29, gpaMid: 3.65, acceptRate: 0.75, ecWeight: 0.68, essayWeight: 0.65, strongGroups: ["engineering","cs_tech","business_econ","bio_health"], state: "PA", isPublic: false, location: "Urban", website: "drexel.edu", legacyBoost: 1.1, diTracked: false, genderNeutral: true },
  { name: "Rensselaer Polytechnic (RPI)", satMid: 1440, actMid: 32, gpaMid: 3.80, acceptRate: 0.55, ecWeight: 0.72, essayWeight: 0.68, strongGroups: ["engineering","cs_tech","math_science"], state: "NY", isPublic: false, location: "Urban", website: "rpi.edu", legacyBoost: 1.1, diTracked: false, genderNeutral: true },
  { name: "Worcester Polytechnic (WPI)", satMid: 1400, actMid: 31, gpaMid: 3.80, acceptRate: 0.56, ecWeight: 0.72, essayWeight: 0.68, strongGroups: ["engineering","cs_tech","math_science"], state: "MA", isPublic: false, location: "Suburban", website: "wpi.edu", legacyBoost: 1.1, diTracked: false, genderNeutral: true },
  { name: "UC Berkeley", satMid: 1430, actMid: 33, gpaMid: 4.15, acceptRate: 0.14, ecWeight: 0.82, essayWeight: 0.80, strongGroups: ["cs_tech","engineering","business_econ","humanities_social"], state: "CA", isPublic: true, location: "Urban", website: "berkeley.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UCLA", satMid: 1420, actMid: 32, gpaMid: 4.15, acceptRate: 0.09, ecWeight: 0.82, essayWeight: 0.80, strongGroups: ["arts_design","bio_health","humanities_social","cs_tech"], state: "CA", isPublic: true, location: "Urban", website: "ucla.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UVA", satMid: 1430, actMid: 33, gpaMid: 4.10, acceptRate: 0.19, ecWeight: 0.82, essayWeight: 0.83, strongGroups: ["business_econ","humanities_social","engineering","cs_tech"], state: "VA", isPublic: true, location: "Suburban", website: "virginia.edu", legacyBoost: 1.2, diTracked: false, genderNeutral: true },
  { name: "UMich Ann Arbor", satMid: 1430, actMid: 33, gpaMid: 3.88, acceptRate: 0.18, ecWeight: 0.83, essayWeight: 0.80, strongGroups: ["engineering","business_econ","cs_tech","humanities_social"], state: "MI", isPublic: true, location: "Suburban", website: "umich.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Georgia Tech", satMid: 1470, actMid: 33, gpaMid: 4.07, acceptRate: 0.17, ecWeight: 0.80, essayWeight: 0.75, strongGroups: ["engineering","cs_tech","math_science","business_econ"], state: "GA", isPublic: true, location: "Urban", website: "gatech.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UNC Chapel Hill", satMid: 1380, actMid: 31, gpaMid: 4.35, acceptRate: 0.19, ecWeight: 0.80, essayWeight: 0.79, strongGroups: ["humanities_social","business_econ","bio_health","arts_design"], state: "NC", isPublic: true, location: "Suburban", website: "unc.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UT Austin", satMid: 1350, actMid: 31, gpaMid: 3.82, acceptRate: 0.29, ecWeight: 0.75, essayWeight: 0.74, strongGroups: ["business_econ","engineering","cs_tech","humanities_social"], state: "TX", isPublic: true, location: "Urban", website: "utexas.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Florida", satMid: 1360, actMid: 31, gpaMid: 4.30, acceptRate: 0.23, ecWeight: 0.75, essayWeight: 0.72, strongGroups: ["engineering","business_econ","bio_health","agriculture"], state: "FL", isPublic: true, location: "Suburban", website: "ufl.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UC San Diego", satMid: 1400, actMid: 32, gpaMid: 4.12, acceptRate: 0.24, ecWeight: 0.75, essayWeight: 0.72, strongGroups: ["bio_health","cs_tech","engineering","math_science"], state: "CA", isPublic: true, location: "Suburban", website: "ucsd.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UC Santa Barbara", satMid: 1360, actMid: 31, gpaMid: 4.10, acceptRate: 0.29, ecWeight: 0.72, essayWeight: 0.70, strongGroups: ["bio_health","engineering","humanities_social","arts_design"], state: "CA", isPublic: true, location: "Suburban", website: "ucsb.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UC Irvine", satMid: 1330, actMid: 30, gpaMid: 4.05, acceptRate: 0.27, ecWeight: 0.70, essayWeight: 0.68, strongGroups: ["cs_tech","bio_health","business_econ","engineering"], state: "CA", isPublic: true, location: "Suburban", website: "uci.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UC Davis", satMid: 1310, actMid: 29, gpaMid: 4.03, acceptRate: 0.39, ecWeight: 0.70, essayWeight: 0.68, strongGroups: ["agriculture","bio_health","engineering","cs_tech"], state: "CA", isPublic: true, location: "Suburban", website: "ucdavis.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "William & Mary", satMid: 1370, actMid: 31, gpaMid: 4.00, acceptRate: 0.37, ecWeight: 0.78, essayWeight: 0.80, strongGroups: ["humanities_social","business_econ","bio_health"], state: "VA", isPublic: true, location: "Suburban", website: "wm.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Maryland", satMid: 1390, actMid: 32, gpaMid: 4.10, acceptRate: 0.44, ecWeight: 0.76, essayWeight: 0.73, strongGroups: ["cs_tech","engineering","business_econ","humanities_social"], state: "MD", isPublic: true, location: "Suburban", website: "umd.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Washington", satMid: 1360, actMid: 31, gpaMid: 3.85, acceptRate: 0.49, ecWeight: 0.74, essayWeight: 0.71, strongGroups: ["cs_tech","engineering","bio_health","business_econ"], state: "WA", isPublic: true, location: "Urban", website: "uw.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Virginia Tech", satMid: 1330, actMid: 30, gpaMid: 3.90, acceptRate: 0.57, ecWeight: 0.70, essayWeight: 0.67, strongGroups: ["engineering","cs_tech","business_econ","agriculture"], state: "VA", isPublic: true, location: "Rural", website: "vt.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Wisconsin", satMid: 1350, actMid: 30, gpaMid: 3.85, acceptRate: 0.49, ecWeight: 0.72, essayWeight: 0.69, strongGroups: ["engineering","business_econ","bio_health","agriculture"], state: "WI", isPublic: true, location: "Urban", website: "wisc.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Purdue", satMid: 1330, actMid: 30, gpaMid: 3.70, acceptRate: 0.53, ecWeight: 0.68, essayWeight: 0.65, strongGroups: ["engineering","cs_tech","agriculture","math_science"], state: "IN", isPublic: true, location: "Suburban", website: "purdue.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Penn State", satMid: 1250, actMid: 28, gpaMid: 3.58, acceptRate: 0.54, ecWeight: 0.65, essayWeight: 0.62, strongGroups: ["engineering","business_econ","humanities_social","agriculture"], state: "PA", isPublic: true, location: "Rural", website: "psu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Ohio State", satMid: 1310, actMid: 29, gpaMid: 3.80, acceptRate: 0.54, ecWeight: 0.67, essayWeight: 0.64, strongGroups: ["business_econ","engineering","bio_health","humanities_social"], state: "OH", isPublic: true, location: "Urban", website: "osu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Florida State", satMid: 1280, actMid: 29, gpaMid: 4.00, acceptRate: 0.25, ecWeight: 0.70, essayWeight: 0.68, strongGroups: ["business_econ","bio_health","humanities_social","arts_design"], state: "FL", isPublic: true, location: "Suburban", website: "fsu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Texas A&M", satMid: 1270, actMid: 29, gpaMid: 3.90, acceptRate: 0.63, ecWeight: 0.68, essayWeight: 0.63, strongGroups: ["engineering","agriculture","business_econ","cs_tech"], state: "TX", isPublic: true, location: "Suburban", website: "tamu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Pittsburgh", satMid: 1360, actMid: 31, gpaMid: 3.90, acceptRate: 0.52, ecWeight: 0.74, essayWeight: 0.71, strongGroups: ["bio_health","business_econ","engineering","humanities_social"], state: "PA", isPublic: true, location: "Urban", website: "pitt.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Connecticut", satMid: 1290, actMid: 29, gpaMid: 3.85, acceptRate: 0.54, ecWeight: 0.68, essayWeight: 0.65, strongGroups: ["business_econ","engineering","bio_health","humanities_social"], state: "CT", isPublic: true, location: "Suburban", website: "uconn.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Rutgers University", satMid: 1300, actMid: 29, gpaMid: 3.90, acceptRate: 0.67, ecWeight: 0.66, essayWeight: 0.62, strongGroups: ["engineering","bio_health","business_econ","humanities_social"], state: "NJ", isPublic: true, location: "Suburban", website: "rutgers.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Colorado Boulder", satMid: 1240, actMid: 28, gpaMid: 3.65, acceptRate: 0.80, ecWeight: 0.62, essayWeight: 0.60, strongGroups: ["engineering","cs_tech","business_econ","arts_design"], state: "CO", isPublic: true, location: "Suburban", website: "colorado.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Arizona State", satMid: 1180, actMid: 25, gpaMid: 3.50, acceptRate: 0.88, ecWeight: 0.55, essayWeight: 0.52, strongGroups: ["business_econ","engineering","cs_tech","humanities_social"], state: "AZ", isPublic: true, location: "Suburban", website: "asu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Indiana University", satMid: 1210, actMid: 27, gpaMid: 3.65, acceptRate: 0.80, ecWeight: 0.60, essayWeight: 0.58, strongGroups: ["business_econ","humanities_social","cs_tech"], state: "IN", isPublic: true, location: "Suburban", website: "indiana.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Michigan State", satMid: 1230, actMid: 27, gpaMid: 3.60, acceptRate: 0.76, ecWeight: 0.60, essayWeight: 0.57, strongGroups: ["business_econ","bio_health","agriculture","engineering"], state: "MI", isPublic: true, location: "Suburban", website: "msu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "Iowa State", satMid: 1180, actMid: 25, gpaMid: 3.55, acceptRate: 0.88, ecWeight: 0.55, essayWeight: 0.52, strongGroups: ["engineering","agriculture","cs_tech","business_econ"], state: "IA", isPublic: true, location: "Suburban", website: "iastate.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Oregon", satMid: 1160, actMid: 25, gpaMid: 3.55, acceptRate: 0.83, ecWeight: 0.58, essayWeight: 0.60, strongGroups: ["business_econ","humanities_social","arts_design","bio_health"], state: "OR", isPublic: true, location: "Suburban", website: "uoregon.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "George Mason", satMid: 1230, actMid: 27, gpaMid: 3.70, acceptRate: 0.83, ecWeight: 0.60, essayWeight: 0.58, strongGroups: ["cs_tech","business_econ","humanities_social","engineering"], state: "VA", isPublic: true, location: "Suburban", website: "gmu.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "UC Santa Cruz", satMid: 1270, actMid: 28, gpaMid: 3.90, acceptRate: 0.47, ecWeight: 0.65, essayWeight: 0.63, strongGroups: ["cs_tech","bio_health","arts_design","humanities_social"], state: "CA", isPublic: true, location: "Suburban", website: "ucsc.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of South Carolina", satMid: 1210, actMid: 26, gpaMid: 3.80, acceptRate: 0.63, ecWeight: 0.62, essayWeight: 0.60, strongGroups: ["business_econ","humanities_social","bio_health"], state: "SC", isPublic: true, location: "Urban", website: "sc.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
  { name: "University of Houston", satMid: 1210, actMid: 26, gpaMid: 3.60, acceptRate: 0.65, ecWeight: 0.62, essayWeight: 0.60, strongGroups: ["engineering","business_econ","cs_tech","bio_health"], state: "TX", isPublic: true, location: "Urban", website: "uh.edu", legacyBoost: 1.0, diTracked: false, genderNeutral: true },
];
